package com.study.plugin.translate.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import java.awt.Dimension;
import java.awt.Insets;
import lombok.Getter;

import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;

public class TranslateConfigUI {
    @Getter
    private JPanel rootJPanel;
    private JTabbedPane youdaoTabbedPanel;
    private JPanel youdaoJPanel;
    private JPanel biyingJPanel;
    private JPanel baiduJPanel;
    private JPasswordField youdaoAppIdTextField;
    private JPasswordField youdaoAppSecretTextField;
    private JPasswordField biyingAppIdTextField;
    private JPasswordField biyingAppSecretTextField;
    private JPasswordField baiduAppIdTextField;
    private JPasswordField baiduAppSecretTextField;
    private JPanel deeplJPanel;
    private JPasswordField deeplAppSecretTextField;
    private JPanel caiyunJPanel;
    private JPasswordField caiyunAppSecretTextField;
    private JTextArea 如果你还没有百度翻译的账号请到httpsAiYoudaoTextArea;
    private JTextArea 必应翻译需要到HttpsCnBingTextArea;
    private JTextArea 百度翻译需要到httpApiFanyiBaiduTextArea;
    private JTextArea 国内无法使用请确保浏览器可调用否则请勿使用TextArea;
    private JTextArea 彩云小译需要到httpsDashboardCaiyunappComTextArea;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootJPanel = new JPanel();
        rootJPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        youdaoTabbedPanel = new JTabbedPane();
        rootJPanel.add(youdaoTabbedPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        youdaoJPanel = new JPanel();
        youdaoJPanel.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        youdaoTabbedPanel.addTab("有道翻译", youdaoJPanel);
        final JLabel label1 = new JLabel();
        label1.setText("应用ID：");
        youdaoJPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("应用秘钥：");
        youdaoJPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        youdaoAppIdTextField = new JPasswordField();
        youdaoJPanel.add(youdaoAppIdTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        youdaoAppSecretTextField = new JPasswordField();
        youdaoJPanel.add(youdaoAppSecretTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        youdaoJPanel.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        如果你还没有百度翻译的账号请到httpsAiYoudaoTextArea = new JTextArea();
        如果你还没有百度翻译的账号请到httpsAiYoudaoTextArea.setEditable(false);
        如果你还没有百度翻译的账号请到httpsAiYoudaoTextArea.setEnabled(false);
        如果你还没有百度翻译的账号请到httpsAiYoudaoTextArea.setText("如果你还没有百度翻译的账号，请到https://ai.youdao.com/?keyfrom=fanyi-new-nav#/注册账号。\n每个账号有50人民币的赠送金额可用。\n差不多是100万字符的翻译。");
        youdaoJPanel.add(如果你还没有百度翻译的账号请到httpsAiYoudaoTextArea, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer2 = new Spacer();
        youdaoJPanel.add(spacer2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        biyingJPanel = new JPanel();
        biyingJPanel.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        youdaoTabbedPanel.addTab("必应翻译", biyingJPanel);
        final JLabel label3 = new JLabel();
        label3.setText("应用ID：");
        biyingJPanel.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        biyingJPanel.add(spacer3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("应用秘钥：");
        biyingJPanel.add(label4, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        biyingAppIdTextField = new JPasswordField();
        biyingJPanel.add(biyingAppIdTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        biyingAppSecretTextField = new JPasswordField();
        biyingJPanel.add(biyingAppSecretTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        必应翻译需要到HttpsCnBingTextArea = new JTextArea();
        必应翻译需要到HttpsCnBingTextArea.setEditable(false);
        必应翻译需要到HttpsCnBingTextArea.setEnabled(false);
        必应翻译需要到HttpsCnBingTextArea.setLineWrap(true);
        必应翻译需要到HttpsCnBingTextArea.setText("必应翻译需要到\nhttps://cn.bing.com/partners/developers?mkt=zh-CN\n注册账号。\n必应需要有微软的Azure账号，要注册Azure账号需要通过信用卡验证，信用卡只支持visa等国际信用卡。");
        biyingJPanel.add(必应翻译需要到HttpsCnBingTextArea, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer4 = new Spacer();
        biyingJPanel.add(spacer4, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        baiduJPanel = new JPanel();
        baiduJPanel.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        youdaoTabbedPanel.addTab("百度翻译", baiduJPanel);
        final JLabel label5 = new JLabel();
        label5.setText("应用ID：");
        baiduJPanel.add(label5, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        baiduJPanel.add(spacer5, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("应用秘钥：");
        baiduJPanel.add(label6, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        baiduAppIdTextField = new JPasswordField();
        baiduJPanel.add(baiduAppIdTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        baiduAppSecretTextField = new JPasswordField();
        baiduJPanel.add(baiduAppSecretTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        百度翻译需要到httpApiFanyiBaiduTextArea = new JTextArea();
        百度翻译需要到httpApiFanyiBaiduTextArea.setEditable(false);
        百度翻译需要到httpApiFanyiBaiduTextArea.setEnabled(false);
        百度翻译需要到httpApiFanyiBaiduTextArea.setText("百度翻译需要到http://api.fanyi.baidu.com/注册账号。\n刚注册账号后需要进行实名认证。\n通过实名认证后，每月200万字符免费。");
        baiduJPanel.add(百度翻译需要到httpApiFanyiBaiduTextArea, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer6 = new Spacer();
        baiduJPanel.add(spacer6, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        deeplJPanel = new JPanel();
        deeplJPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        youdaoTabbedPanel.addTab("DeepL", deeplJPanel);
        final JLabel label7 = new JLabel();
        label7.setText("验证秘钥：");
        deeplJPanel.add(label7, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer7 = new Spacer();
        deeplJPanel.add(spacer7, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        deeplAppSecretTextField = new JPasswordField();
        deeplJPanel.add(deeplAppSecretTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        国内无法使用请确保浏览器可调用否则请勿使用TextArea = new JTextArea();
        国内无法使用请确保浏览器可调用否则请勿使用TextArea.setEditable(false);
        国内无法使用请确保浏览器可调用否则请勿使用TextArea.setEnabled(false);
        国内无法使用请确保浏览器可调用否则请勿使用TextArea.setText("国内无法使用，请确保浏览器可调用，否则请勿使用。");
        deeplJPanel.add(国内无法使用请确保浏览器可调用否则请勿使用TextArea, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer8 = new Spacer();
        deeplJPanel.add(spacer8, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        caiyunJPanel = new JPanel();
        caiyunJPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        youdaoTabbedPanel.addTab("彩云小译", caiyunJPanel);
        final JLabel label8 = new JLabel();
        label8.setText("令牌：");
        caiyunJPanel.add(label8, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer9 = new Spacer();
        caiyunJPanel.add(spacer9, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        caiyunAppSecretTextField = new JPasswordField();
        caiyunJPanel.add(caiyunAppSecretTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        彩云小译需要到httpsDashboardCaiyunappComTextArea = new JTextArea();
        彩云小译需要到httpsDashboardCaiyunappComTextArea.setEditable(false);
        彩云小译需要到httpsDashboardCaiyunappComTextArea.setEnabled(false);
        彩云小译需要到httpsDashboardCaiyunappComTextArea.setText("彩云小译需要到https://dashboard.caiyunapp.com/user/user/info/#注册账号。\n注册完账后后需要通过人工审核，人工审核节假日较慢。\n(因为我的账号还未通过审核，因此不知道彩云小译的定价情况)");
        caiyunJPanel.add(彩云小译需要到httpsDashboardCaiyunappComTextArea, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer10 = new Spacer();
        caiyunJPanel.add(spacer10, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootJPanel;
    }

    public String getYoudaoAppId() {
        return String.valueOf(youdaoAppIdTextField.getPassword()).trim();
    }

    public String getYoudaoAppSecret() {
        return String.valueOf(youdaoAppSecretTextField.getPassword()).trim();
    }

    public String getBiyingAppId() {
        return String.valueOf(biyingAppIdTextField.getPassword()).trim();
    }

    public String getBiyingAppSecret() {
        return String.valueOf(biyingAppSecretTextField.getPassword()).trim();
    }

    public String getBaiduAppId() {
        return String.valueOf(baiduAppIdTextField.getPassword()).trim();
    }

    public String getBaiduAppSecret() {
        return String.valueOf(baiduAppSecretTextField.getPassword()).trim();
    }

    public String getDeeplAppSecret() {
        return String.valueOf(deeplAppSecretTextField.getPassword()).trim();
    }

    public String getCaiyunAppSecret() {
        return String.valueOf(caiyunAppSecretTextField.getPassword()).trim();
    }

    public void setYoudaoAppId(String youdaoAppId) {
        youdaoAppIdTextField.setText(youdaoAppId);
    }

    public void setYoudaoAppSecret(String youdaoAppSecret) {
        youdaoAppSecretTextField.setText(youdaoAppSecret);
    }

    public void setBiyingAppId(String biyingAppId) {
        biyingAppIdTextField.setText(biyingAppId);
    }

    public void setBiyingAppSecret(String biyingAppSecret) {
        biyingAppSecretTextField.setText(biyingAppSecret);
    }

    public void setBaiduAppId(String baiduAppId) {
        baiduAppIdTextField.setText(baiduAppId);
    }

    public void setBaiduAppSecret(String baiduAppSecret) {
        baiduAppSecretTextField.setText(baiduAppSecret);
    }

    public void setDeeplAppSecret(String deeplAppSecret) {
        deeplAppSecretTextField.setText(deeplAppSecret);
    }

    public void setCaiyunAppSecret(String caiyunAppSecret) {
        caiyunAppSecretTextField.setText(caiyunAppSecret);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("TranslateConfigUI");
        frame.setContentPane(new TranslateConfigUI().rootJPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
}
